baseURL = 'https://ssheersh.github.io'
languageCode = 'en-us'
title = 'Samyak Sheersh'
theme = 'ananke'
resourceDir = '../reosources'

[params]
twitter = 'https://twitter.com/SamyakSheersh'
linkedin = 'https://www.linkedin.com/in/samyak-sheersh-8bb852192/'
github = 'github.com/ssheersh'
